"""
Test for Investigate mode SLA thresholds completeness.

Validates that all generated task names have corresponding SLA thresholds
for bottleneck analysis.
"""

import pytest


class TestInvestigateSLAThresholds:
    """Test that SLA thresholds cover all generated tasks."""

    def test_all_task_names_have_thresholds(self):
        """Ensure all Investigate tasks have SLA thresholds defined."""
        # These are the task names generated by InvestigateUser
        # Based on test_investigate_load.py task methods and their name= parameters
        generated_tasks = [
            "Page Load",
            "Prime Filters",
            "Prime Analysis",
            "Update Filters",  # Lines 211-253, name=f"Update Filters ({filter_preset})"
            "Analyze Data",     # Line 275, name="Analyze Data"
            "Navigate to Investigation",
            "Render Investigation View",
            "Point Drilldown",
            "Navigate Back",
        ]

        # Expected thresholds from module docstring and review requirements
        # Review feedback indicates "Update Filters" should have 1000ms threshold
        # and "Analyze Data" should have a threshold (likely 3000ms like analysis)
        expected_thresholds = {
            "Page Load": 500,
            "Prime Filters": 1000,
            "Prime Analysis": 3000,
            "Update Filters": 1000,  # Must be included (review feedback)
            "Analyze Data": 3000,    # Must be included (review feedback)
            "Navigate to Investigation": 500,
            "Render Investigation View": 3000,
            "Point Drilldown": 1500,
            "Navigate Back": 500,
        }

        # Verify all generated tasks have thresholds
        for task in generated_tasks:
            assert task in expected_thresholds, f"Task '{task}' missing SLA threshold"

        # Verify thresholds are reasonable (positive integers)
        for task, threshold in expected_thresholds.items():
            assert isinstance(threshold, int), f"Threshold for '{task}' must be int"
            assert threshold > 0, f"Threshold for '{task}' must be positive"
            assert threshold < 10000, f"Threshold for '{task}' seems too high"

    def test_threshold_dict_structure(self):
        """Test that the thresholds dict has the correct structure."""
        thresholds = {
            "Page Load": 500,
            "Prime Filters": 1000,
            "Prime Analysis": 3000,
            "Update Filters": 1000,
            "Analyze Data": 3000,
            "Navigate to Investigation": 500,
            "Render Investigation View": 3000,
            "Point Drilldown": 1500,
            "Navigate Back": 500,
        }

        # Check required keys exist
        assert "Update Filters" in thresholds
        assert "Analyze Data" in thresholds

        # Check they have reasonable values
        assert thresholds["Update Filters"] == 1000
        assert thresholds["Analyze Data"] == 3000

    def test_base_name_extraction_works(self):
        """Test that preset suffix is properly stripped for threshold lookup."""
        # Task names are generated as "Update Filters (small|medium|large)"
        # The bottleneck analysis should strip the preset suffix
        task_names = [
            "Update Filters (small)",
            "Update Filters (medium)",
            "Update Filters (large)",
        ]

        # Base name extraction logic from test_investigate_load.py:519-521
        for task_name in task_names:
            if " (" in task_name:
                base_name = task_name.split(" (")[0]
            else:
                base_name = task_name

            assert base_name == "Update Filters"
